### ISSUE TITLE
Bug in delete_many

### ISSUE THREAD

**Issue by vkameswaran** [getmetal/metal-python#26]
I'm running into an issue with the `delete_many` method ([this one](https://github.com/getmetal/metal-python/blob/main/src/metal_sdk/metal.py#L152-L160)) in the Metal client. When the request is successful, the server returns a `<Response [204 No Content]>` object, but when the client then tries to parse this response as JSON, it generates an exception (below). I think the return value just needs to be adjusted to avoid this.

```
Traceback (most recent call last):
  File "/Users/vaishant/Desktop/test/delete.py", line 22, in <module>
    metal.delete_many([doc['id'] for doc in results['data']])
  File "/Users/vaishant/Desktop/test/lib/python3.9/site-packages/metal_sdk/metal.py", line 161, in delete_many
    return res.json()
  File "/Users/vaishant/Desktop/test/lib/python3.9/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Thanks!

**Comment by Czechh** [comment]
Thank you for bringing this up!
